ecomapp/urls.py
from xmlrpc.client import APPLICATION_ERROR
from django.urls import path
from .views import*
from . import views
app_name="ecomapp"
urlpatterns=[
    path("", HomeView.as_view(),name="home"),
    path("about/", AboutView.as_view(),name="about"),
    path("contact-us/", ContactView.as_view(),name="contact"),
    path("all-products/", AllProductsView.as_view(),name="allproducts"),
    path("product/<slug:slug>/", ProductDetailView.as_view(),name="productdetail"),
    path("add-to-cart-<int:pro_id>/",AddToCartView.as_view(),name="addtocart"),
    path("my-cart/",MyCartView.as_view(),name="mycart"),
    path("manage-cart/<int:cp_id>/",ManageCartView.as_view(),name="managecart"),
    path("empty-cart/",EmptyCartView.as_view(),name="emptycart"),
    path("checkout/",CheckoutView.as_view(),name="checkout"),
    path("register/",CustomerRegistrationView.as_view(),name="customerregistration"),
    path("logout/",CustomerLogoutView.as_view(),name="customerlogout"),
    path("login/",CustomerLoginView.as_view(),name="customerlogin"),
    path("profile/",CustomerProfileView.as_view(),name="customerprofile"),


    path("profile/order-<int:pk>/",CustomerOrderDetailView.as_view(),name="customerorderdetail"),
    path("mydashboard/",MyDashboardView.as_view(),name="orderedbooks"),


    path("search/",SearchView.as_view(),name="search"),
    path("searchauthor/",SearchAuthorView.as_view(),name="searchauthor"),
    path("searchbookname/",SearchBookNameView.as_view(),name="searchbookname"),
    path("searchcategory/",SearchCategoryView.as_view(),name="searchcategory"),

    # path("want-to-sell/",WantToSellView.as_view(),name="wanttosell"),
    # path("review/", views.Review_rate, name="review"),
    path("forgot-password/", PasswordForgotView.as_view(), name="passwordforgot"),
    path("password-reset/<email>/<token>/",PasswordResetView.as_view(),name="passwordreset"),
    path('dashboard/',views.dashboard,name="dashboard"),
    # customer  product upload starts here
    path("customer-product/add/", CustomerProductCreateView.as_view(),name="customerproductcreate"),

    path("gen_pdf/", views.gen_pdf, name="gen_pdf"),
    path("gen1_pdf/", views.gen1_pdf, name="gen1_pdf"),
    path("gen2_pdf/", views.gen2_pdf, name="gen2_pdf"),

    # admin side
    # path("admin-product/list/",AdminProductListView.as_view(),name="adminproductlist"),
    # path("admin-product/add/",AdminProductCreateView.as_view(),name="adminproductcreate"),

]

ecomproject/urls.py
import imp
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static  
urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("ecomapp.urls")),
]
# urlpatterns+=static()
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecomapp/models.py
from concurrent.futures.process import _MAX_WINDOWS_WORKERS
from distutils.command.upload import upload
import email
from email.policy import default
from importlib.machinery import FrozenImporter
from operator import truediv
from pyexpat import model
from tkinter import CASCADE
from typing import Tuple
from unittest.util import _MAX_LENGTH
from django.contrib.auth.models import User
from statistics import mode
from unicodedata import category
from django.db import models
from django.forms import CharField

# Create your models here.
# class Coupon(models.Model):
#     code=CharField(max_length=15)

#     def __str__(self):
#         return self.code






class Contact(models.Model):
    name = models.CharField(max_length=20,null=False,blank=False)
    email = models.CharField(max_length=20,null=False,blank=False)
    phone = models.CharField(max_length=20,null=False,blank=False)
    desc = models.CharField(max_length=500,null=False,blank=False)

    def __str__(self):
        return self.email





class Customer(models.Model):
    user=models.OneToOneField(User, on_delete=models.CASCADE)
    full_name=models.CharField(max_length=200,null=False,blank=False)
    address= models.CharField(max_length=300,null=False,blank=False)
    joined_on=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.full_name

class Category(models.Model):
    title=models.CharField(max_length=200)
    slug=models.SlugField(unique=True)


    def __str__(self):
        return self.title


class Product(models.Model):
    title=models.CharField(max_length=200,null=False,blank=False)
    author=models.CharField(max_length=100,null=False,blank=False)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    slug=models.SlugField(unique=True,null=False,blank=False)
    image=models.ImageField(upload_to="products") 
    marked_price=models.PositiveBigIntegerField(null=False,blank=False)
    selling_price=models.PositiveBigIntegerField(null=False,blank=False)
    description=models.TextField(null=False,blank=False)
    # warranty=models.CharField(max_length=300,null=True,blank=True)
    # return_policy=models.CharField(max_length=300,null=True,blank=True)
    view_count=models.PositiveIntegerField(default=0)
    quantity=models.PositiveBigIntegerField(default=0)
    # user= models.ForeignKey(User,on_delete=models.CASCADE)


    def __str__(self):
        return self.title


class ProductImage(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    image=models.ImageField(upload_to="products/images/")

    def __str__(self):
        return self.product.title

# class ProductUpload(models.Model):
#     customer=models.CharField(max_length=100,blank=False,null=False)
#     # customer=models.ForeignKey(Customer,on_delete=models.CASCADE)
#     # product=models.ForeignKey(Product,on_delete=models.CASCADE)



    def __str__(self):
        return "Product: " + str(self.id)


class Cart(models.Model):
    customer=models.ForeignKey(Customer,on_delete=models.SET_NULL,null=True,blank=True)
    total=models.PositiveBigIntegerField(default=0)
    created_at=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Cart:"+str(self.id)

class CartProduct(models.Model):
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    rate=models.PositiveBigIntegerField(default=0)
    quantity=models.PositiveBigIntegerField(default=0)
    subtotal=models.PositiveBigIntegerField(default=0)


    def __str__(self):
        return "Cart:"+str(self.cart.id) + "CartProduct: " + str(self.id)


ORDER_STATUS= (
     ("Order Received","Order Received"),
     ("Order Processing","Order Processing"),
     ("On the way","On the way"),
     ("Completed","Completed"),
     ("Order Cancelled", "Order Cancelled"),
 )
class Order(models.Model):
     cart=models.OneToOneField(Cart, on_delete=models.CASCADE)
     ordered_by=models.CharField(max_length=200,null=False,blank=False)
     shipping_address=models.CharField(max_length=300,null=False,blank=False)
     mobile=models.CharField(max_length=11)
     email=models.CharField(max_length=100,null=False,blank=False)
     subtotal=models.PositiveBigIntegerField(default=0)
     total=models.PositiveBigIntegerField(default=0)
     order_status=models.CharField(max_length=200,choices=ORDER_STATUS)
     created_at=models.DateTimeField(auto_now_add=True)



     def __str__(self):
        return "Order: " + str(self.id)

class Rating(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,default=None)
    movie=models.ForeignKey(Product,on_delete=models.CASCADE,default=None)
    rating=models.CharField(max_length=70)
    rated_date=models.DateTimeField(auto_now_add=True)

templates/addtocart.html
{% extends 'base.html' %}
{% block title %}Add To Cart{% endblock %}
{% block content %}
 <div class="container">
     <h3 style="color:black;">Product Added To Cart Successfully</h3>
 </div>
{% endblock %}

templates/allproducts.html
{% extends 'base.html' %}

{% block title %} All Products {% endblock %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'ecomapp/css/category.css' %}">

 <div class="container">
     <h3  class="text-center">All Categories</h3><hr>
     {% for cat in allcategories %}
     <h3  class="my-3">{{cat.title}}</h3>
     <hr>
     <div class="row">
        {% for p in cat.product_set.all %}
        <div class="col-md-3  card">
            <div class="m-4">
        <h4><a class="textupdt"  href="{% url 'ecomapp:productdetail' p.slug %}">{{p.title}}</a></h4>
        <img class="check" src="{{p.image.url}}" alt="" class="img-fluid">
        <p ><strong>Rs:{{p.selling_price}}</strong></p>
        {% if p.quantity > 0 %}
        <!-- <p ><strong>Rs:{{p.selling_price}}</strong></p>s -->
        <a href="{% url 'ecomapp:addtocart' p.id  %}" class="btn btn-light my-3">Add To Cart</a>
        <b class="link-success"><p>In Stock Available</p></b>
        {% else %}
        <b class="link-danger my-2" ><p>Out of Stock</p></b>
        {% endif %} 
    </div>
    </div>
        {% endfor %}

     </div>
     {% endfor %}
 </div>
 {% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
    rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Sofia&effect=neon|outline|emboss|shadow-multiple">
  <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<style media="screen">
/* body {
    background: linear-gradient(-45deg, #ee7752, #e73c7e, #23a6d5, #23d5ab);
    background-size: 400% 400%;
    animation: gradient 15s ease infinite;
      font: 400 16px/1.5 exo, ubuntu, "segoe ui", helvetica, arial, sans-serif;
    text-align: center;
} */
/*
@keyframes gradient {
    0% {
        background-position: 0% 50%;
    }
    50% {
        background-position: 100% 50%;
    }
    100% {
        background-position: 0% 50%;
    }
} */

.glow {
  color: #fff;
  text-align: center;
  animation: glow 1s ease-in-out infinite alternate;
}

@keyframes glow {
  from {
    text-shadow: 0 0 10px #fff, 0 0 20px #fff, 0 0 30px #e60073, 0 0 40px #e60073, 0 0 50px #e60073, 0 0 60px #e60073, 0 0 70px #e60073;
  }

  to {
    text-shadow: 0 0 20px #fff, 0 0 30px #ff4da6, 0 0 40px #ff4da6, 0 0 50px #ff4da6, 0 0 60px #ff4da6, 0 0 70px #ff4da6, 0 0 80px #ff4da6;
  }
}
body{
  display: grid;
  top: 0;
  left: 0;
  margin: 0;
  padding: 0;
  color: white;
  background-image:radial-gradient(ellipse at bottom left, rgba(0,163,203,1) 40%, rgba(0,163,203,0) 40%),
    radial-gradient(ellipse at top right, rgba(0,163,203,1) 30%, rgba(0,163,203,0) 30%),
    linear-gradient(to right, rgba(98,87,147,1) 0%, rgba(98,87,147,1) 33%, rgba(213,93,100,1) 33%, rgba(213,93,100,1) 66%, rgba(228,145,41,1) 66%);
  text-align: center;

  }
  h1,h2,h3,h4,h5,h6{
    color: #00008b;
  }
</style>
  </head>
  <body >
<style>

#navtest  {
  height: 70px;
  border: 1px solid rgba(0, 0, 0, 0.125);
  box-shadow: 0 15px 25px rgba(129, 124, 124, 0.2);
  border-radius: 5px;
  backdrop-filter: blur(14px);
  background-color: rgba(255, 255, 255, 0.2);
}
li a:hover {
  background-color:#296354;
  border-radius: 50px;
}


.nav-item{
  font-size: 1em;
  font-family: emoji;

}
li:last-child {
  border-right: none;
}
.nav-logo{
  height: 30px;
  width: 100px;
}
.pull-right {
    margin-right: 30px;
    padding-left: 400px;
}
.navbar{
  z-index: 2;
}
.dropdown-menu{

  background-color:#2e6b5c ;
}
.button-color{
  background-color: red;
}

</style>



    <!--  you can also call pathe by their nemae in following syntax -->
    <!-- <a href="/">Home</a> -->

    <nav id="navtest" class="navbar  navbar-expand-lg navbar-dark p-2 font-weight-bold" >
      <a class="navbar-brand font-weight-bold" href="{% url 'ecomapp:home' %}">Book Trekker  <img src='/media/products/logo.png' class="nav-logo" alt="..."></a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon font-weight-bold"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">

            <a class="nav-link " href="{% url 'ecomapp:home' %}"><span>
                <i class="fa fa-home"></i>
              Home </span></a
            >
          </li>
          <li class="nav-item ">
            <a class="nav-link " href="/all-products/"><i class="fa fa-bar-chart" aria-hidden="true"></i> Categories</a>
          </li>

          <li class="nav-item ">
            <a class="nav-link " href="/about/"><i class="fa fa-address-card" aria-hidden="true"></i> AboutUs</a>
          </li>

          <li class="nav-item ">
            <a class="nav-link " href="/contact-us/">
              <i class="fa fa-fw fa-envelope"></i> ContactUs</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/my-cart/"><i class="fa fa-shopping-cart"></i> Cart</a>
          </li>
          <li class="nav-item dropdown">
            <a
              class="nav-link dropdown-toggle"
              href="#"
              id="navbarDropdown"
              role="button"
              data-toggle="dropdown"
              aria-haspopup="true"
              aria-expanded="false"
            >
              Reports
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">

              <a class="dropdown-item" href="/gen_pdf/">Products</a>
              <a class="dropdown-item" href="/gen1_pdf/">Users</a>
              <a class="dropdown-item" href="/gen2_pdf/">Carts</a>
            </div>
          </li>
          <li class="nav-item">
            <a class=" nav-link" href="{% url 'ecomapp:customerproductcreate' %}"><i class="fa fa-plus-square-o" aria-hidden="true"></i> Sell</a>
            <!-- <a class="nav-link" href="/want-to-sell/">Want to Sell?</a> -->
          </li>
          <li class="nav-item dropdown">
            <a
              class="nav-link dropdown-toggle"
              href="#"
              id="navbarDropdown"
              role="button"
              data-toggle="dropdown"
              aria-haspopup="true"
              aria-expanded="false"
            >
            <i class="fa fa-fw fa-user"></i>   MyAccount
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% if request.user.customer %}
              <a class="dropdown-item " href="/profile/"> My Profile </a>
              <a class="dropdown-item" href="/logout/"> Logout </a>
              <a class="dropdown-item" href="/dashboard/">Feedback</a>
              {% else %}
              <a class="dropdown-item" href="/register/">Register</a>
              <a class="dropdown-item" href="/login/">Login</a>
              {% endif %}
            </div>
          </li>
          <li>
            <div class="dropdownSearch"  >
              <button type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               <i> Search Here For Your Choice</i>
                </button>



               <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <b><p class="mx-3 my-0">Search </p></b>
                <form class="form-inline my-2 my-lg-0" action="{% url 'ecomapp:search' %}"  >
                  <input  name="keyword" class="form-control mr-sm-2 my-0 text-right" type="search" placeholder="Search" aria-label="Search"
                  required>
                      </form>

                     <b> <p class="mx-3 my-0">Book Name </p></b>
                <form class="form-inline my-2 my-lg-0" action="{% url 'ecomapp:searchbookname' %}"  >
                  <input  name="bookname" class="form-control mr-sm-2 my-0 text-right" type="search" placeholder="Search" aria-label="Search"
                  required>
                      </form>

                      <b><p class="mx-3 my-0">By Author </p></b>
                <form class="form-inline my-2 my-lg-0" action="{% url 'ecomapp:searchauthor' %}"  >
                  <input  name="bookauthor" class="form-control mr-sm-2 my-0 text-right" type="search" placeholder="Search" aria-label="Search"
                  required>
                      </form>


                      <b><p class="mx-3 my-0">By Category </p></b>
                <form class="form-inline my-2 my-lg-0" action="{% url 'ecomapp:searchcategory' %}"  >
                  <input  name="bookcategory" class="form-control mr-sm-2 my-0 text-right" type="search" placeholder="Search" aria-label="Search"
                  required>
                      </form>
                    </div>





                  <!-- <div class="pull-right">
                        <form
                        class="form-inline my-2 my-lg-0 "action="{% url 'ecomapp:search' %}"  >
                          <input  name="keyword" class="form-control mr-sm-2 my-2 text-centre" type="search" placeholder="Search" aria-label="Search"
                            required
                          />
                         <div class="button-color">
                          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                        </div>
                        </form>

                      </div> -->

                  </div>
          </li>

        </ul>



    </nav>
  </div>
    <!-- <a href="/contact-us/">Contact Us</a>
      <a href="/all-products/">Categories</a>
      <a href="/my-cart/">View Cart</a> -->
    <hr />

    {% block content %} {% endblock %}
    {% block js %}{% endblock %}

    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/checkout.html
{% extends 'base.html' %}
{% block title %}Checkout-Book Trekker{% endblock %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'ecomapp/css/cart.css' %}">
<div class="container">
    <div class="row">
        <div class="col-md-6">
        <h3>Items in the cart</h3>
        <p>Want to update cart ?</p><a style="color:greenyellow" href="{% url 'ecomapp:mycart' %}"> Click Here</a>
            <table class="table" style="color:blue;">
                <thead>
                    <tr>
                        <th>Sn</th>
                        <th>Product</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>SubTotal</th>

                    </tr>
                </thead>
                <tbody>
                    {% for cp in cart.cartproduct_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{cp.product.title}}</td>
                        <td>{{cp.rate}}</td>
                        <td>{{cp.quantity}}</td>
                        <td>{{cp.subtotal}}</td>
                        </tr>
                        {% endfor %}
                        <tr>
                            <th colspan="4" class="text-right">Total</th>
                            <th>Rs. {{cart.total}}</th>
                        </tr>
                        </tbody>
                        </table>

                    </div>
        <div class="col-md-6">
            <h3>Checkout form</h3>
            <form action="" method="POST">
                {% csrf_token %}
                <b style="color:blue;">{{form.as_p}}</b>

                <button class="btn btn-primary">Place Order</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/confirm_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% if success %}
    account verified
    {% else %}
    Error , invalid token
    {% endif %}
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block title %}Home-Book Trekker{% endblock %}
{% block content  %}
{% load static %}

<link rel="stylesheet" href="{% static 'ecomapp/css/home.css' %}">

<div class="container">
  <!-- <div id="slider">
  					  <figure>
  						    <img src="<img src='/media/products/f1.jpg">
  						    <img src="<img src='/media/products/h2.jpg">
  						    <img src="<img src='/media/products/r3.jpg">
  					  </figure>
  </div> -->
    <h1 id="welcome" class=" mt-3 my-3" >Welcome To Book Trekker</h1>
    <div class="row">
    {% for p in product_list %}
    <div class="col-md-3 card">
        <div class="m-4">
            <h4 ><a class="my-3" href="{% url 'ecomapp:productdetail' p.slug %}">{{p.title}}</a></h4>
    <img src="{{p.image.url}}" class="check"  alt="" >
    <p class="my-3" style="color:black;"><strong>Rs: {{p.selling_price}}</strong></p>
    {% if p.quantity > 0 %}
    <a href="{% url 'ecomapp:addtocart' p.id  %}" id="middle" class="btn btn-warning">Add To Cart</a>

    <b class="link-success"><p>In Stock Available</p></b>
    {% else %}
    <b class="link-danger my-2" ><p>Out of Stock</p></b>
    {% endif %}
    <!-- <link rel="stylesheet" type="text/css" href="{% static 'ecomapp/css/style.css' %}"/> -->
</div>
</div>
    {% endfor %}
</div>

<nav aria-label="...">
    <ul class="pagination">
        {% if product_list.has_previous %}
        <!-- previous page login -->
        <li class="page-item ">
            <a class="page-link" href="?page={{ product_list.previous_page_number }}" >Previous</a>
          </li>
        {% else %}

      <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1">Previous</a>
      </li>

      {% endif %}
      {% for i in product_list.paginator.page_range %}
      {% if i == product_list.number %}
      <li class="page-item active"><a class="page-link" >{{i}}</a></li>
      {% else %}
      <li class="page-item "><a class="page-link" href="?page={{i }}">{{i}}</a></li>
      {% endif %}
      {% endfor %}
      <!-- Next page logic -->
      {% if product_list.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ product_list.next_page_number }}">Next</a>
      </li>
      {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1">Next</a>
      </li>

      {% endif %}
    </ul>
  </nav>
</div>

<div class="container wrapper">
{% if  recommended%}
  <h1 id="welcome" class=" mt-3 my-3" >Recommended Books For You</h1>
  <div class="row">

{% for item in recommended %}

<div class="col-md-3 card">
<div class="m-4">
  {% for p in all_products %}
  <!-- {% if item.pro_id == p.id %} -->
<h4 ><a class="my-3" href="{% url 'ecomapp:productdetail' item.slug %}">{{item.title}}</a></h4>
<!-- {% endif %} -->
{% endfor %}
                <img class="card-img-top" src="{{item.image}}"  alt="Card image cap" height="250px" width="200px">
                
                <div class="card-footer">

                </div>
        </div>
</div>
{% endfor %}
</div>
{% else %}
<h1 id="welcome" class=" mt-3 my-3" >No Recommended Books Found</h1>
{% endif %}
{% endblock %}

templates/mycart.html
{% extends 'base.html' %}
{% block title %}My Cart{% endblock %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'ecomapp/css/cart.css' %}">

<!-- {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %} style="color:green"> {{message }}</li>
    {% endfor %}
</ul>

{% endif %} -->


<ul class="messages" id="messages-list">
    {% if messages %}
        {% for message in messages %}
        <li>
            {% if message.tags %}
                 <div class="alert alert-{{ message.tags }} msg fade show" role="alert">{{ message }}</div>
            {% else %}
                <div class="alert alert-info msg fade show" role="alert">{{ message }}</div>
            {% endif %}
        </li>
        {% endfor %}
    {% endif %}
    </ul>
<div class="container">
    <div class="row">
        <div class="col-md-8">
            {% if cart.cartproduct_set.all %}
            <h4 style="color:dark-blue;">Items in my cart </h4><hr>
            <table class="table" style="color:blue;">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Product</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cp in cart.cartproduct_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{cp.product.title}}</td>
                        <td>{{cp.rate}}</td>
                        <td>{{cp.quantity}}</td>
                        <td>{{cp.subtotal}}</td>
                        <td>
                            <a href="{% url 'ecomapp:managecart' cp.id %}?action=inc" class="btn btn-primary"> + </a>
                            <a href="{% url 'ecomapp:managecart' cp.id %}?action=dcr" class="btn btn-warning"> - </a>
                            <a href="{% url 'ecomapp:managecart' cp.id %}?action=rmv" class="btn btn-danger"> x </a>
                        </td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th colspan="4" class="text-center">Total</th>
                        <th>
                            <b>Rs. {{cart.total}}</b>
                        </th>
                        <!-- {% if cart.cartproduct_set.all  %} -->
                        <th><a href="{% url 'ecomapp:emptycart' %}">Empty Cart</a>   </th>
                        <!-- {% endif %} -->

                    </tr>
                    <!-- {% if cart.cartproduct_set.all %} -->
                    <tr>
                        <th><a class="btn btn-primary" href="{% url 'ecomapp:checkout' %}"> Checkout</a></th>

                    </tr>
                    <!-- {% endif %} -->

                </tbody>

            </table>
            {% else %}
        <h4 style="color:black;">Please Make sure to add books in your cart</h4><hr>
       {% endif %}

        </div>

    </div>

</div>


{% endblock %}